language: python
sudo: enabled
node_js:
  - '0.10'

notifications:
  email:
    recipients:
      - tonyejck@gmail.com

before_script:
  - npm install 
  - pip install -e .[test] --no-deps
  - touch service_account.json
  - echo {"type": "service account", "client_id": "12233"} >> service_account.json
  - touch client_id.json
  - touch google_api_keys.json
  
  
script:
  make test
  make tox
