language: python
sudo: enabled
node_js:
  - '0.10'

notifications:
  email:
    recipients:
      - tonyejck@gmail.com

before_script:
  - npm install 
  - pip install -e .[test] --no-deps
  - "echo { \"type\": \"service account\", \"client_id\": \"12233\" } >> service_account.json"
  - "echo { \"web\": {\"client_id\": \"103m\", \"client_secret\": \"abc1234\"} } >> client_id.json"
  - "echo { \"maps-api-key\": \"J0sQpA\", \"fusion-table-api-key\": \"KMQ\", \"client-secret\": \"f7TlA\" } >> google_api_keys.json"
  
script:
  make test
  make tox
