language: python
sudo: enabled
node_js:
  - '6.0'
python:
  - "2.7"
  - "3.6"

notifications:
  email:
    recipients:
      - tonyejck@gmail.com

install:
  - wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
  - tar xJf Python-3.6.3.tar.xz
  - rm Python-3.6.3.tar.xz
  - cd Python-3.6.3
  - ./configure
  - sudo make
  - sudo make install
  - cd ..
  - pip install -e . -r requirements.txt
  - sudo apt-get install python-tox

before_script:
  - npm install 
  - pip install -e .[test]

script:
  - make test
  - tox
