
environment:
  - PYTHON: "C:\\Python36-x64"

# Install scripts. (runs after repo cloning)
install:
  - npm install 
  - pip install -e . -r requirements.txt

# Before running test create dummy files.
before_test:
  - pip install -e .[test]

# Post-install test scripts.
test_script:
  # run tests
  - make test
  - tox

build: off
